function [fitresult, gof] = tanhfit2(I, maxspeed)
%CREATEFIT(I,MAXSPEED)
%  Create a fit.
%
%  Data for 'tanhfit2' fit:
%      X Input : I
%      Y Output: maxspeed
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Feb-2014 18:19:23


%% Fit: 'tanhfit2'.
[xData, yData] = prepareCurveData( I, maxspeed );

% Set up fittype and options.
ft = fittype( 'tanh(b*(x-c))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf];
opts.StartPoint = [0.141886338627215 0.421761282626275];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'tanhfit2' );
h = plot( fitresult, xData, yData );
legend( h, 'maxspeed vs. I', 'tanhfit2', 'Location', 'NorthEast' );
% Label axes
xlabel( 'I' );
ylabel( 'maxspeed' );
grid on


