function [fitresult, gof] = tanhfit(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Jan-2014 18:06:18


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( '(a*tanh(b*(x-c)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf];
opts.StartPoint = [0.913375856139019 0.63235924622541 0.0975404049994095];
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Maxspeed vs Laser power', 'a*tanh(b*(x-c))', 'Location', 'SouthEast' );
% Label axes
xlabel( 'Laser power' );
ylabel( 'Max reverse speed' );
text(130,20,['a =' num2str(fitresult.a)])
text(130,15,['b =' num2str(fitresult.b)])
text(130,10,['c =' num2str(fitresult.c)])



