# This function utilize LASSO algorithm to find the best linear prediction model of laser power from centroid speed data.
# This function requires glmnet and R.matlab package.
# 
# Input:
#   folderpath -- path to the folder which contain centroid speed data.
#   datafname -- filename of the .mat file which contains centroid speed data.
# 
# Return:
#   Maximum cross validated R square.
# 
# Output File:
#   LASSO results generated by different lambdas will be stored in a file named 'LASSO_result.mat' in the same folder as specified in folderpath.
# 
# Output file structure:
#   nzero(i) -- number of non-zeros coefficients of index i. 
#   r2cv(i) -- Cross-validated R square of index i.
#   LASSOresult(j,i) -- The coefficients of the linear model of index i.
# 
# Output Figures:
#   1. Cross validated R square vs number of non-zeros
#   2. Coefficients of the model at maximum R square
# 
# 
# (c) George Leung, Ilya Nemenman, Emory University, 2011-2013
# 


LASSO <- function(folderpath,datafname){

# loading the  libraries
library("R.matlab")
library("glmnet")


# change to the folder which contain centroid speed data
setwd(folderpath)

#read centroid speed data
mattest <- readMat(file.path(datafname))


#Assign input
predict = mattest$nfspeed
newI = t(mattest$I)


#Setting Lambda range 
lambdafit1 = seq(log(20),log(0.0005),length=100) 
lambdafit1 = exp(lambdafit1)

#LASSO
fit1 = glmnet(t(predict), t(newI),lambda=lambdafit1)

#Cross-validated LASSO
fit2 = cv.glmnet(t(predict), t(newI),lambda=lambdafit1)
r2cv= 1- (fit2$cvm/var(newI))


#output Rsquare vs no. of nonzeros plot
windows(1) 
plot(fit2$nzero,r2cv,col="red",xlab="no. of non-zero coefficients",ylab='Rsquare',ylim=c(0,1))
title('Rsquare')
xlab='Rsquare'


#Plot the coefficients at the maximum value of Rsquare
windows() 
plot(fit1$beta[,which.max(r2cv)],xlab='time',ylab='value of the coefficients')
title(r2cv[which.max(r2cv)],  sub = fit2$nzero[which.max(r2cv)],
      cex.sub = 0.75, font.sub = 3, col.sub = "red")


#save data into R_result.mat
writeMat("LASSO_result.mat",r2cv=r2cv, LASSOresult=fit1$beta, nzero=fit1$df)

#Return maximum r square 
  return(max(r2cv))
}
