function [fitresult, gof] = logFit(inputy, inputx)
%CREATEFIT(INPUTY,INPUTX)
%  Create a fit.
%
%  Data for 'fit1' fit:
%      X Input : inputy
%      Y Output: inputx
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Nov-2013 03:55:36


%% Fit: 'fit1'.
[xData, yData] = prepareCurveData( inputy, inputx );

% Set up fittype and options.
ft = fittype( 'a*log( b*x + 1)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [0 0];
opts.StartPoint = [0.91333736150167 0.152378018969223];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'fit1' );
h = plot( fitresult, xData, yData );

% Label axes
xlabel( 'inputy' );
ylabel( 'inputx' );
grid on


