
function []=nonlineartran(speeddatapath, datafilename,modelfilepath,modelfilename)

% function []=nonlineartran(speeddatapath, datafilename,maxspeeddatapath,maxspeedfilename)
% 
% This function will apply nonlinear transform to laser power by fitting a
% exponential curve to the maximum centroid speed verse laser power data. 
% 
% Input:
%  speeddatapath -- path to the file with the centroid velocity data and
%  model file data
%  datafilename -- filename of the centroid velocity data file,
% 	extension '.mat' is assumed
%  modelfilepath --
%  modelfilename -- path to the file with the maximum centroid velocity
%  data generated by feature.m
% 
% Input file structure:
% centroid velocity data:
% 	fspeed (i,j) -- filtered centroid velocity at time i of trial j.
%   nfspeed (i,j) -- filtered and normalized centroid veloctiy at time i of trial j.
%   I(i) -- laser power of worm i.
% maximum centroid velocity data:
%   fitresult -- nonlinear transform model
% 
% Output:
%  no output variables
% 
% Output File:
% 
% Output file structure:
% 	fspeed (i,j) -- filtered centroid velocity at time i of trial j.
%   nfspeed (i,j) -- filtered and normalized centroid veloctiy at time i of trial j.
%   I(i) -- Transformed laser power of worm i.
% 
% (c) George Leung, Ilya Nemenman, Emory University, 2011-2013

%load data
load([speeddatapath '/' datafilename '.mat'])
load([modelfilepath '/' modelfilename '.mat'])

I= fitresult(I)';

save([speeddatapath '\' datafilename '_nonlinearsp.mat'], 'I','fspeed','nfspeed')

end