function [fitresult, gof] = smoothingspline(inputx, inputy,param)
%CREATEFIT(INPUTX,INPUTY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : inputx
%      Y Output: inputy
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-Nov-2013 17:20:17


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( inputx, inputy );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( ft );
opts.SmoothingParam = param;
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'inputy vs. inputx', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'inputx' );
ylabel( 'inputy' );
grid on


